import type { Metadata } from 'next'
import { Be_Vietnam_Pro } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'
import { Navbar } from '@/components/index'
import Footer from '@/components/layout/Footer'

const vietnam = Be_Vietnam_Pro({
  subsets: ['latin'],
  variable: '--font-vietnam',
  weight: ['100', '200', '300', '400'],
})

const canela = localFont({
  src: './../../public/canela-regular.woff',
  variable: '--font-canela',
})

const canelaMedium = localFont({
  src: './../../public/canela-medium.woff',
  variable: '--font-canelaMedium',
})

const canelaThin = localFont({
  src: './../../public/canela-thin.woff',
  variable: '--font-canelaThin',
})

export const metadata: Metadata = {
  title: 'Heritage',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`overflow-x-hidden ${canelaThin.variable} ${canelaMedium.variable} ${canela.variable} ${vietnam.variable}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
